modLoader="javafml"
loaderVersion="[1,)"
license="GPL v3.0"

[[mods]]
modId="scrollable_tooltips"
version="${file.jarVersion}"
displayName="Scrollable Tooltips"
displayURL="https://sk1er.club/mods/text_overflow_scroll"
description="Allows for scrolling on tooltips"

[[mixins]]
config="mixins.scrollabletooltips.json"

[[dependencies.scrollable_tooltips]]
modId="kotlinforforge"
mandatory=true
versionRange="[0,)"